export const ADD_POST = 'ADD_POST';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGOUT = 'USER_LOGOUT';
// export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const USER_SEARCH = 'USER_SEARCH';
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const ADD_FRIEND = "ADD_FRIEND";
export const MANAGE_FRIEND_REQUEST = "MANAGE_FRIEND_REQUEST";
export const CHANGE_POST = "CHANGE_POST";
export const NEW_POST = "NEW_POST";
export const DELETE_POST = "DELETE_POST";
export const DELETE_FRIEND = "DELETE_FRIEND";
export const UDPATE_USER_IFNO = "UDPATE_USER_IFNO";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const GET_POST_LIST = "GET_POST_LIST";
